[profile.default]
retries = 2
failure-output = "immediate-final"
fail-fast = { max-fail = 10 }
# temporarily disable S3 tests
default-filter = 'not binary(s3_tests)'

[profile.ci]
# Do not cancel the test run on the first failure
fail-fast = false
retries = 2
failure-output = "immediate-final"
# temporarily disable S3 tests
default-filter = 'not binary(s3_tests)'
